
import java.io.IOException;
import java.io.InputStream;
import java.util.Enumeration;
import java.util.TooManyListenersException;
  // import javax.comm.CommPortIdentifier;
import javax.comm.PortInUseException;
//import javax.comm.SerialPort;
//import javax.comm.SerialPortEvent;
 //  import javax.comm.SerialPortEventListener;
import javax.comm.UnsupportedCommOperationException;

import gnu.io.CommPortIdentifier; 
import gnu.io.SerialPort;
import gnu.io.SerialPortEvent; 
import gnu.io.SerialPortEventListener;
import java.awt.Dimension;
import java.awt.Panel;
import java.io.ByteArrayOutputStream;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.Date;


import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Elisabete
 */
public class Receive extends javax.swing.JFrame implements Runnable, SerialPortEventListener{

    /**
     * Creates new form Receive
     */
    static CommPortIdentifier portId;
    static Enumeration portList;
    InputStream inputStream;
    SerialPort serialPort;
    Thread readThread;
    public Receive() {
        initComponents();
   
    }
    int cont = 0;
    long end , start;
    int forca1,forca2,forca3,forca4;
    int n = 1;
    int forca11=0,forca21=0,forca31=0,forca41=0;
    int forca12=0,forca22=0,forca32=0,forca42=0;
    int forca13=0,forca23=0,forca33=0,forca43=0;
    int forca14=0,forca24=0,forca34=0,forca44=0;
    int forca15=0,forca25=0,forca35=0,forca45=0;
    int forca16=0,forca26=0,forca36=0,forca46=0;
    int forca17=0,forca27=0,forca37=0,forca47=0;
    int forca18=0,forca28=0,forca38=0,forca48=0;
    int forca19=0,forca29=0,forca39=0,forca49=0;
    int forca110=0,forca210=0,forca310=0,forca410=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        panel5 = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        panel6 = new java.awt.Panel();
        panel7 = new java.awt.Panel();
        panel8 = new java.awt.Panel();
        panel9 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jButton1.setText("Portas Disponiveis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Desconectar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Time:");

        jLabel1.setText("Tempo de voo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(281, 281, 281)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(524, 524, 524)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Configurações", jPanel1);

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField6.setText("jTextField6");

        jTextField9.setText("jTextField9");

        jTextField10.setText("jTextField9");

        jTextField11.setText("jTextField9");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jLabel2.setText("Força 1:");

        jLabel3.setText("Força 2:");

        jLabel4.setText("Força 3:");

        jLabel5.setText("Força 4:");

        jLabel6.setText("Tempo :");

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jTextField2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Pulo", jPanel4);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField12.setText("jTextField12");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField12)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 752, Short.MAX_VALUE)
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(362, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Matriz", jPanel5);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField13.setText("jTextField13");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField13)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 765, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Peso", jPanel2);

        jTabbedPane1.addTab("Plataforma", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        java.util.Enumeration<CommPortIdentifier> portEnum = CommPortIdentifier.getPortIdentifiers();
       // Enumeration portEnum = CommPortIdentifier.getPortIdentifiers();
        //System.out.println("alguma porta tem:"+ portEnum);
        int i = 0;
        String[] r = new String[5];

        while (portEnum.hasMoreElements() && i < 5) {
           // CommPortIdentifier portIdentifier = (CommPortIdentifier) portEnum.nextElement();
            CommPortIdentifier portIdentifier = portEnum.nextElement();

            r[i] = portIdentifier.getName();//+  " - " +  getPortTypeName(portIdentifier.getPortType()) ;


            i++;

System.out.println("portas"+r[i]);
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(r));
        //System.out.println("entrou aqui");
       // System.out.println("portas"+r[0]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Object selectedItem = jComboBox1.getSelectedItem();

        String com = selectedItem.toString();
        SimpleRead(com);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        serialPort.close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       // while(true){
        // converte int para string
        //while(true){
        String f1 = Integer.toString(forca1);
        String f2 = Integer.toString(forca2);
        String f3 = Integer.toString(forca3);
        String f4 = Integer.toString(forca4);
        
        //coloca os valores nas boxs
        jTextField6.setText(f1);
        jTextField9.setText(f2);
        jTextField10.setText(f3);
        jTextField11.setText(f4);
        
        //adicona valores no grafico
        if(n == 1){
            set1(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca1,forca12,forca13,forca14,forca15,forca16,forca17,forca18,forca19,forca110,"Força 1","MV","N");
        createGraphic(panel2,forca2,forca22,forca23,forca24,forca25,forca26,forca27,forca28,forca29,forca210,"Força 2","MV","N");
        createGraphic(panel3,forca3,forca32,forca33,forca34,forca35,forca36,forca37,forca38,forca39,forca310,"Força 3","MV","N");
        createGraphic(panel4,forca4,forca42,forca43,forca44,forca45,forca46,forca47,forca48,forca49,forca410,"Força 4","MV","N");
            n=2;
        }else if(n ==2){
            set2(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca11,forca1,forca13,forca14,forca15,forca16,forca17,forca18,forca19,forca110,"Força 1","MV","N");
        createGraphic(panel2,forca21,forca2,forca23,forca24,forca25,forca26,forca27,forca28,forca29,forca210,"Força 2","MV","N");
        createGraphic(panel3,forca31,forca3,forca33,forca34,forca35,forca36,forca37,forca38,forca39,forca310,"Força 3","MV","N");
        createGraphic(panel4,forca41,forca4,forca43,forca44,forca45,forca46,forca47,forca48,forca49,forca410,"Força 4","MV","N");
        n=3;
        }else if(n ==3){
            set3(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca11,forca12,forca1,forca14,forca15,forca16,forca17,forca18,forca19,forca110,"Força 1","MV","N");
        createGraphic(panel2,forca21,forca42,forca2,forca24,forca25,forca26,forca27,forca28,forca29,forca210,"Força 2","MV","N");
        createGraphic(panel3,forca31,forca42,forca3,forca34,forca35,forca36,forca37,forca38,forca39,forca310,"Força 3","MV","N");
        createGraphic(panel4,forca41,forca42,forca4,forca44,forca45,forca46,forca47,forca48,forca49,forca410,"Força 4","MV","N");
        n=4;
        }else if(n ==4){
            set4(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca11,forca12,forca13,forca1,forca15,forca16,forca17,forca18,forca19,forca110,"Força 1","MV","N");
        createGraphic(panel2,forca21,forca42,forca23,forca2,forca25,forca26,forca27,forca28,forca29,forca210,"Força 2","MV","N");
        createGraphic(panel3,forca31,forca42,forca33,forca3,forca35,forca36,forca37,forca38,forca39,forca310,"Força 3","MV","N");
        createGraphic(panel4,forca41,forca42,forca43,forca4,forca45,forca46,forca47,forca48,forca49,forca410,"Força 4","MV","N");
        n=5;
        }else if(n ==5){
            set5(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca11,forca12,forca13,forca14,forca1,forca16,forca17,forca18,forca19,forca110,"Força 1","MV","N");
        createGraphic(panel2,forca21,forca42,forca23,forca24,forca2,forca26,forca27,forca28,forca29,forca210,"Força 2","MV","N");
        createGraphic(panel3,forca31,forca42,forca33,forca34,forca3,forca36,forca37,forca38,forca39,forca310,"Força 3","MV","N");
        createGraphic(panel4,forca41,forca42,forca43,forca44,forca4,forca46,forca47,forca48,forca49,forca410,"Força 4","MV","N");
        n=6;
        }else if(n ==6){
            set6(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca11,forca12,forca13,forca14,forca15,forca1,forca17,forca18,forca19,forca110,"Força 1","MV","N");
        createGraphic(panel2,forca21,forca42,forca23,forca24,forca25,forca2,forca27,forca28,forca29,forca210,"Força 2","MV","N");
        createGraphic(panel3,forca31,forca42,forca33,forca34,forca35,forca3,forca37,forca38,forca39,forca310,"Força 3","MV","N");
        createGraphic(panel4,forca41,forca42,forca43,forca44,forca45,forca4,forca47,forca48,forca49,forca410,"Força 4","MV","N");
        n=7;
        }else if(n ==7){
            set7(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca11,forca12,forca13,forca14,forca15,forca16,forca1,forca18,forca19,forca110,"Força 1","MV","N");
        createGraphic(panel2,forca21,forca42,forca23,forca24,forca25,forca26,forca2,forca28,forca29,forca210,"Força 2","MV","N");
        createGraphic(panel3,forca31,forca42,forca33,forca34,forca35,forca36,forca3,forca38,forca39,forca310,"Força 3","MV","N");
        createGraphic(panel4,forca41,forca42,forca43,forca44,forca45,forca46,forca4,forca48,forca49,forca410,"Força 4","MV","N");
        n=8;
        }else if(n ==8){
            set8(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca11,forca12,forca13,forca14,forca15,forca16,forca17,forca1,forca19,forca110,"Força 1","MV","N");
        createGraphic(panel2,forca21,forca42,forca23,forca24,forca25,forca26,forca27,forca2,forca29,forca210,"Força 2","MV","N");
        createGraphic(panel3,forca31,forca42,forca33,forca34,forca35,forca36,forca37,forca3,forca39,forca310,"Força 3","MV","N");
        createGraphic(panel4,forca41,forca42,forca43,forca44,forca45,forca46,forca47,forca4,forca49,forca410,"Força 4","MV","N");
        n=9;
        }else if(n ==9){
            set9(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca11,forca12,forca13,forca14,forca15,forca16,forca17,forca18,forca1,forca110,"Força 1","MV","N");
        createGraphic(panel2,forca21,forca42,forca23,forca24,forca25,forca26,forca27,forca28,forca2,forca210,"Força 2","MV","N");
        createGraphic(panel3,forca31,forca42,forca33,forca34,forca35,forca36,forca37,forca38,forca3,forca310,"Força 3","MV","N");
        createGraphic(panel4,forca41,forca42,forca43,forca44,forca45,forca46,forca47,forca48,forca4,forca410,"Força 4","MV","N");
        n=10;
        }else if(n ==10){
            set10(forca1,forca2,forca3,forca4);
        createGraphic(panel1,forca11,forca12,forca13,forca14,forca15,forca16,forca17,forca18,forca19,forca1,"Força 1","MV","N");
        createGraphic(panel2,forca21,forca42,forca23,forca24,forca25,forca26,forca27,forca28,forca29,forca2,"Força 2","MV","N");
        createGraphic(panel3,forca31,forca42,forca33,forca34,forca35,forca36,forca37,forca38,forca39,forca3,"Força 3","MV","N");
        createGraphic(panel4,forca41,forca42,forca43,forca44,forca45,forca46,forca47,forca48,forca49,forca4,"Força 4","MV","N");
        n=1;
        }
       // }

    }//GEN-LAST:event_jButton3ActionPerformed

    
    public void set1(int a,int b,int c, int d){
        forca11 = a;
        forca21 = b;
        forca31 = c;
        forca41 = d;       
    }
    public void set2(int a,int b,int c, int d){
        forca12 = a;
        forca22 = b;
        forca33 = c;
        forca42 = d;
    }
    public void set3(int a,int b,int c, int d){
        forca13 = a;
        forca23 = b;
        forca33 = c;
        forca43 = d;
    }
    public void set4(int a,int b,int c, int d){
        forca14 = a;
        forca24 = b;
        forca34 = c;
        forca44 = d;
    }
    public void set5(int a,int b,int c, int d){
        forca15 = a;
        forca25 = b;
        forca35 = c;
        forca45 = d;
    }
    public void set6(int a,int b,int c, int d){
        forca16 = a;
        forca26 = b;
        forca36 = c;
        forca46 = d;
    }
    public void set7(int a,int b,int c, int d){
        forca17 = a;
        forca27 = b;
        forca37 = c;
        forca47 = d;
    }
    public void set8(int a,int b,int c, int d){
        forca18 = a;
        forca28 = b;
        forca38 = c;
        forca48 = d;
    }
    public void set9(int a,int b,int c, int d){
        forca19 = a;
        forca29 = b;
        forca39 = c;
        forca49 = d;
    }
    public void set10(int a,int b,int c, int d){
        forca110 = a;
        forca210 = b;
        forca310 = c;
        forca410 = d;
    }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
       /* createGraphic(panel5,1,2,3,"Força 1","MV","N");
        jTextField12.setText("");*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
       /* createGraphic(panel6,1,2,3,"Força 1","MV","N");
        
        createGraphic(panel7,1,2,3,"Força 2","MV","N");
        
        createGraphic(panel8,1,2,3,"Força 3","MV","N");
        
        createGraphic(panel9,1,2,3,"Força 4","MV","N");
       jTextField13.setText("");*/
    }//GEN-LAST:event_jButton5ActionPerformed

   // public String convert (){
        
    //    return
   // }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receive().setVisible(true);
                
            }
        });
    }

    public void SimpleRead(String com) {
        portList = CommPortIdentifier.getPortIdentifiers();

        while (portList.hasMoreElements()) {
            portId = (CommPortIdentifier) portList.nextElement();
            if (portId.getPortType() == CommPortIdentifier.PORT_SERIAL) {
                if (portId.getName().equals(com)) {
                    //                if (portId.getName().equals("/dev/term/a")) {
                    try {
                       // serialPort = (SerialPort) portId.open("SimpleReadApp", 2000);
                        
                        // open serial port, and use class name for the appName.
			serialPort = (SerialPort) portId.open(this.getClass().getName(),
					2000);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                    try {
                        inputStream = serialPort.getInputStream();
                    } catch (IOException e) {
                        System.out.println(e);
                    }
                    try {
                        serialPort.addEventListener(this);
                    } catch (TooManyListenersException e) {
                        System.out.println(e);
                    }
                    serialPort.notifyOnDataAvailable(true);
                    try {
                        serialPort.setSerialPortParams(115200,
                                SerialPort.DATABITS_8,
                                SerialPort.STOPBITS_1,
                                SerialPort.PARITY_NONE);
                        
                        // set port parameters
			
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                    readThread = new Thread(this);
                    readThread.start();
                }
            }
        }

    }

    public void run() {
        try {
            Thread.sleep(20000);
        } catch (InterruptedException e) {
            System.out.println(e);
        }
    }

    public void serialEvent(SerialPortEvent event) {
      //  new Thread() {
			
		//	@Override
		//	public void run() {
        switch (event.getEventType()) {
            case SerialPortEvent.BI:
            case SerialPortEvent.OE:
            case SerialPortEvent.FE:
            case SerialPortEvent.PE:
            case SerialPortEvent.CD:
            case SerialPortEvent.CTS:
            case SerialPortEvent.DSR:
            case SerialPortEvent.RI:
            case SerialPortEvent.OUTPUT_BUFFER_EMPTY:
                break;
            case SerialPortEvent.DATA_AVAILABLE:
                byte[] readBuffer = new byte[8];
                

                
                ByteArrayOutputStream buffer = new ByteArrayOutputStream();

                try {
                    while (inputStream.available() > 0) {
                        //int numBytes = inputStream.read(readBuffer);
                        
                        // read stream data into buffer
                        inputStream.read(readBuffer);

                    }
                    /*buffer.write(readBuffer);
                    System.out.println("SAIU");
                    byte[] byteArray2 = buffer.toByteArray();
                    System.out.println("HOW DOES OUR ARRAY LOOKS LIKE");
                    System.out.println(byteArray2);*/
                    
                    
                    
                    for (int k =0  ;k < readBuffer.length; k+=2){
                        System.out.println("VALOR DE K NO FOR ---->" + k);
                        byte a = (byte)readBuffer[k];
                        System.out.println("valor do byte A --->" + a);
                        int valorDeK = k + 1;
                        byte b = (byte)readBuffer[valorDeK];
                        System.out.println("valor do byte B --->" + b);
                        String intNovo = Integer.toString(a, 2);
                        String intNovo2 = Integer.toString(b, 2);
                        byte[] novo = intNovo.getBytes();
                        System.out.println("ARRAY DE BYTE NOVO");
                        System.out.println(novo);
                        byte[] novo2 = intNovo2.getBytes();
                        System.out.println("NOVO E ACHO QUE FINAL");
                        //byte[] c = new byte[novo + novo2];
                        
                        ByteArrayOutputStream outputStream = new ByteArrayOutputStream( );
                        outputStream.write( novo );
                        outputStream.write( novo2 );
                        System.out.println("BYTE ARRAY OUTPUT");
                        System.out.println(outputStream);
                        String oiOi = outputStream.toString();
                        System.out.println(oiOi);
                        int decimalValue = Integer.parseInt(outputStream.toString(), 2);
                        System.out.println(decimalValue);
                        if(k == 0){
                        setValue(decimalValue,forca2,forca3,forca4);
                        }else if(k == 2){
                        setValue(forca1,decimalValue,forca3,forca4);
                        }else if (k == 4){
                         setValue(forca1,forca2,decimalValue,forca4);   
                        }else if (k==6){
                            setValue(forca1,forca2,forca3,decimalValue);
                        }
                        
                        System.out.println("FIIIIIM");
                        byte c[] = outputStream.toByteArray();
                        System.out.println("NOVO E ACHO QUE FINAL");
                        int i = new BigInteger(c).intValue(); 
                        System.out.println("AGORAAA");
                        System.out.println(i);
                        
                        
                        /*ByteArrayOutputStream novoByte = new ByteArrayOutputStream();

                        novoByte.write(a);
                        novoByte.write(b);

                        System.out.println("NOSSO LINDO E GOSTOSO BYTE FINAL");
                        System.out.println(Arrays.toString(novoByte.toByteArray()));
                        System.out.println(novoByte.toString());*/
                    }

                    //
                    //char c = y.charAt(0);
                   // char c = y.charAt(0);
                    //System.out.println(inputStream);
                    String y = new String(readBuffer);
                    
                    //int a = Integer.parseInt(y);
                    
                     /*   int a = Integer.parseInt(y);
                        System.out.println(a);
                        forca2 =2;
                    forca3 =3;
                    forca4=4;
                    setValue(a,forca2,forca3,forca4);*/
                    diferenca(y);
                    
                    
                    
                    
                    
                } catch (IOException e) {
                    System.out.println(e);
                }catch(NumberFormatException ex){ // handle your exception
   
                    }
                break;
        }
        
        	//}
		//}.start();
    }
    public int toInt( byte[] bytes ) {
        int result = 0;
        for (int i=0; i<4; i++) {
          result = ( result << 8 ) - Byte.MIN_VALUE + (int) bytes[i];
        }
        return result;
      }

    public void setValue(int a,int b,int c,int d){
        forca1 = a;
        forca2 = b;
        forca3 = c;
        forca4 = d;
    }
    
    
    
    
    public void diferenca(String readBuffer){
        
       // DefaultCategoryDataset ds = createData();
        
       // panel1.add(grafico);
         if(cont == 0){
                    
                   
                    //System.out.print(new String(readBuffer));
                    //jTextField1.setText("    " + y + "    ");
                    //pega a data atual
                    Date date = new Date();
                    jTextField5.setText( date.toString());
                   
                    //pega o tempo inicial
                    start = System.currentTimeMillis( );
                    waiting(1);
                    cont = 1;
                    }else if(cont == 1){
                        
                    String y = new String(readBuffer);
                   
                  //  System.out.print(new String(readBuffer));
                    //jTextField1.setText("    " + y + "    ");
                    //pega a data atual
                    Date date = new Date();
                    jTextField5.setText( date.toString());
                    //pega o tempo final
                    end = System.currentTimeMillis( );
                    waiting(1);
                    cont = 2;
                    }
                    if(cont == 2){
                        long diff = end - start;
                         System.out.println("Difference is : " + diff);
                        String dif = Long.toString(diff);
                        jTextField1.setText(dif +" ms");
                         jTextField2.setText(dif +" ms");
                        cont = 0;
                    }
                        
    }
    
    
    ////////
    public static void waiting(int n) {

        long t0, t1;

        t0 = System.currentTimeMillis();

        do {
            t1 = System.currentTimeMillis();
        } while ((t1 - t0) < (n * 1000));
    }
    ////////////
    
    /**********************************/
    /*  Função para criação de dados */
    /*********************************/
    /* @return */
    public static DefaultCategoryDataset createData(int a,int b, int c,int d,int e,int f,int g,int h,int i, int j){
        // cria o conjunto de dados
        DefaultCategoryDataset ds = new DefaultCategoryDataset();
        ds.addValue(a, "Newton", "dia 1");
        ds.addValue(b, "Newton", "dia 2");
        ds.addValue(c, "Newton", "dia 3");
        ds.addValue(d, "Newton", "dia 4");
        ds.addValue(e, "Newton", "dia 5");
        ds.addValue(f, "Newton", "dia 6");
        ds.addValue(g, "Newton", "dia 4");
        ds.addValue(h, "Newton", "dia 5");
        ds.addValue(i, "Newton", "dia 6");
        ds.addValue(j, "Newton", "dia 4");
        
        return ds; 
    }
    
    /***************************************/
    /* Criar grafico e adicionar no jframe */
    /**************************************/
    /* @param panel */
    public static void createGraphic(Panel panel,int a,int b, int c,int d,int e,int f,int g,int h,int i, int j, String Titulo,String X,String Y){
        
        DefaultCategoryDataset ds = createData(a,b,c,d,e,f,g,h,i,j);
        
        // cria o gráfico
        JFreeChart grafico = ChartFactory.createLineChart(Titulo, X, 
            Y, ds, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel myChartPanel = new ChartPanel(grafico, true);
        myChartPanel.setSize(panel.getWidth(),panel.getHeight());
        myChartPanel.setVisible(true);
        panel.removeAll();
        panel.add(myChartPanel);
        panel.revalidate();
        panel.repaint();
    }
            
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    private java.awt.Panel panel8;
    private java.awt.Panel panel9;
    // End of variables declaration//GEN-END:variables
}
